export const GET_SEARCH_REQUESTED = 'GET_SEARCH_REQUESTED';
export const GET_SEARCH_SUCCEEDED = 'GET_SEARCH_SUCCEEDED';
export const GET_SEARCH_FAILED = 'GET_SEARCH_FAILED';

export const SET_SEARCH_FILTER_KEYWORD = 'SET_SEARCH_FILTER_KEYWORD';
export const SET_SEARCH_FILTER_ORDER = 'SET_SEARCH_FILTER_ORDER';
